version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .

  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r9 deployment_package.zip . -x buildspec.yml "*.git*" "*.DS_Store*"
  
  post_build:
    commands:
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name aws-deploy-test --zip-file fileb://deployment_package.zip
      - echo "DONE!!"

artifacts:
  files:
    - deployment_package.zip
